import os
import shutil
import sys
import unittest
import sqlite3
import json
from unittest.mock import MagicMock

# Mock the airflow package and its operators before importing solar_pipeline_dag
mock_airflow = MagicMock()
sys.modules['airflow'] = mock_airflow
sys.modules['airflow.operators'] = MagicMock()
sys.modules['airflow.operators.bash'] = MagicMock()
sys.modules['airflow.operators.python'] = MagicMock()

# Import the tasks to be tested
from solar_pipeline_dag import task_download_imagery, task_generate_config, task_post_process

class MockDagRun:
    def __init__(self, conf=None):
        self.conf = conf or {}

class TestSolarPipelineDAG(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Create a clean data retrieval directory structure for testing
        cls.test_job_name = "test_airflow_integration_job"
        cls.base_dir = "data/inference"
        cls.job_dir = os.path.join(cls.base_dir, cls.test_job_name)
        cls.db_path = "data/solar_jobs.db"
        
        # Clean up any existing test directory
        if os.path.exists(cls.job_dir):
            shutil.rmtree(cls.job_dir)

    @classmethod
    def tearDownClass(cls):
        # Clean up created files and folders after tests
        if os.path.exists(cls.job_dir):
            shutil.rmtree(cls.job_dir)

    def test_end_to_end_pipeline_tasks(self):
        # 1. Prepare Mock context with configurations
        conf = {
            "job_name": self.test_job_name,
            # Use a very small bounding box around SIIT for testing to fetch few tiles
            "min_lat": 14.0700,
            "min_lon": 100.6020,
            "max_lat": 14.0710,
            "max_lon": 100.6030,
            "zoom": 18
        }
        
        mock_dag_run = MockDagRun(conf=conf)
        context = {"dag_run": mock_dag_run}
        
        # 2. Test Task 1: task_download_imagery
        print("\n--- Running Task 1: task_download_imagery ---")
        task_download_imagery(**context)
        
        expected_tif = os.path.join(self.job_dir, "input", "satellite.tif")
        self.assertTrue(os.path.exists(expected_tif), "Satellite TIF file should be downloaded")
        print("✔ Task 1 succeeded! TIF file generated.")

        # 3. Test Task 2: task_generate_config
        print("\n--- Running Task 2: task_generate_config ---")
        task_generate_config(**context)
        
        expected_toml = os.path.join(self.job_dir, f"{self.test_job_name}.toml")
        self.assertTrue(os.path.exists(expected_toml), "TOML config file should be generated")
        print("✔ Task 2 succeeded! TOML config file generated.")

        # 4. Simulate Task 3: Mock model execution (creating corrected shapefile)
        print("\n--- Simulating Task 3: execute_run_sh_model ---")
        import subprocess
        # Run mock_model.py with the generated toml config
        cmd = ["python", "mock_model.py", "--config", expected_toml]
        result = subprocess.run(cmd, capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, f"mock_model.py failed: {result.stderr}")
        
        output_dir = os.path.join(self.job_dir, "output")
        expected_shp = os.path.join(output_dir, f"{self.test_job_name}-corrected.shp")
        self.assertTrue(os.path.exists(expected_shp), "Corrected shapefile should be generated by mock_model")
        print("✔ Simulating Task 3 succeeded! Shapefile generated.")

        # 5. Test Task 4: task_post_process
        print("\n--- Running Task 4: task_post_process ---")
        task_post_process(**context)
        
        expected_geojson = os.path.join(self.job_dir, "result.geojson")
        self.assertTrue(os.path.exists(expected_geojson), "Result GeoJSON should be generated")
        print("✔ Task 4 succeeded! GeoJSON file generated.")

        # 6. Verify Summary JSON and Database
        print("\n--- Verifying Summary JSON and Database ---")
        
        # Check summary.json
        expected_summary = os.path.join(self.job_dir, "summary.json")
        self.assertTrue(os.path.exists(expected_summary), "Summary JSON should be generated")
        with open(expected_summary, "r", encoding="utf-8") as f:
            summary_data = json.load(f)
            self.assertEqual(summary_data["job_name"], self.test_job_name)
            self.assertEqual(summary_data["status"], "completed")
            print(f"✔ Summary JSON verified! Total Panels: {summary_data['total_panels']}")

        # Check SQLite Database
        self.assertTrue(os.path.exists(self.db_path), "Database file should exist")
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute(
            "SELECT polygon_count, total_panels, total_capacity_kwp FROM job_results WHERE job_name = ?",
            (self.test_job_name,),
        )
        row = cursor.fetchone()
        conn.close()
        
        self.assertIsNotNone(row, "Job record should be found in database")
        self.assertEqual(row[0], summary_data["polygon_count"])
        self.assertEqual(row[1], summary_data["total_panels"])
        print(f"✔ Database record verified! Detected {row[0]} polygons, {row[1]} panels, {row[2]} kWp.")

if __name__ == "__main__":
    unittest.main()
